name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
  
      - name: Build SIPPY
        uses: ./.github/actions/install-env  # Path to your composite action
        with:
          python-version: ${{ matrix.python-version }}
          with-dev: "true"

      - name: Run tests
        run: |
          poetry run pytest -m "not datasets" --durations=10 --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
